version: '3'
services:
  db_review:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - data:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=django
      - POSTGRES_DB=microservicoreview
    ports:
      - "8001:5432"

  review:
    build: 
      context: ./servicos/review/
      dockerfile: Dockerfile
    container_name: MicroServicoReview
    command: sh -c "sleep 5 && cd servicos/review/MicroServicoReview && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_review

  broker:
    build:
      context: ./broker/
      dockerfile: Dockerfile
    container_name: Broker
    command: sh -c "cd broker/broker && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - review

volumes:
  data: